# name: 支付宝
# package: com.eg.android.AlipayGphone
# verified: false
# description: 隔离支付宝截图和临时文件
# authors: PathGuard Community

[com.eg.android.AlipayGphone]
mode = blacklist
enabled = true
media_query = auto

- DCIM
alipay/screenshot -> Android/data/com.eg.android.AlipayGphone/cache/screenshot
