# name: 哔哩哔哩
# package: tv.danmaku.bili
# verified: true
# description: 隔离 B 站缓存，防止视频缓存出现在相册
# authors: PathGuard Community

[tv.danmaku.bili]
mode = blacklist
enabled = true
media_query = auto

- DCIM
- Pictures
bili_video -> Android/data/tv.danmaku.bili/cache/bili_video
