# name: 钉钉
# package: com.alibaba.android.rimet
# verified: false
# description: 隔离钉钉接收文件
# authors: PathGuard Community

[com.alibaba.android.rimet]
mode = blacklist
enabled = true
media_query = auto

- DCIM
DingTalk -> Android/data/com.alibaba.android.rimet/files/DingTalk_hidden
