# name: 快手
# package: com.smile.gifmaker
# verified: false
# description: 隔离快手视频缓存
# authors: PathGuard Community

[com.smile.gifmaker]
mode = blacklist
enabled = true
media_query = auto

- DCIM
kuaishou/video -> Android/data/com.smile.gifmaker/cache/video
