# name: QQ
# package: com.tencent.mobileqq
# verified: true
# description: 隔离 QQ 接收文件，防止污染根目录
# authors: PathGuard Community

[com.tencent.mobileqq]
mode = whitelist
enabled = true
media_query = auto

+ DCIM/Camera
+ Pictures/QQ
Tencent/QQfile_recv -> Android/data/com.tencent.mobileqq/Tencent/QQfile_recv_hidden
