# name: 微信
# package: com.tencent.mm
# verified: true
# description: 隔离微信媒体文件，防止 DCIM 污染
# authors: PathGuard Community

[com.tencent.mm]
mode = whitelist
enabled = true
media_query = auto

+ DCIM/Camera
+ Pictures/WeiXin
- DCIM/A-TEST
DCIM/Camera -> Android/data/com.tencent.mm/cache/Camera
