# name: 微博
# package: com.sina.weibo
# verified: false
# description: 隔离微博图片缓存，防止相册污染
# authors: PathGuard Community

[com.sina.weibo]
mode = blacklist
enabled = true
media_query = auto

- DCIM
weibo/image -> Android/data/com.sina.weibo/cache/image
