# name: 小红书
# package: com.xingin.xhs
# verified: false
# description: 隔离小红书下载内容，防止相册污染
# authors: PathGuard Community

[com.xingin.xhs]
mode = blacklist
enabled = true
media_query = auto

- DCIM
- Pictures
xhs_download -> Android/data/com.xingin.xhs/cache/download
